apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- custom-metrics-apiservice.yaml
- metrics-server.yaml
- grafana-ingress.yaml
- grafana-pvc.yaml
- jitsi-dashboard-configmap.yaml
- bbb-dashboards-configmap.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleSpecificNamespaces.yaml
- jvb-pod-monitor.yaml
- prosody-pod-monitor.yaml
- bbb-service.yaml
- bbb-service-monitor.yaml
- bbb-exporter-service-monitor.yaml
- turn-service.yaml
- turn-service-monitor.yaml
- haproxy-pod-monitor.yaml
- grafana-deployment-patch.yaml # Added
- prometheus-adapter-config-map-patch.yaml # Added
- monitoring-namespace.yaml # Added

patchesStrategicMerge:
- metrics-server-patch.yaml

