steps:
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'metacontroller'
    args:
      - 'apply'
      - '-k'
      - 'https://github.com/metacontroller/metacontroller/manifests/production/'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
  - id: 'Resources'
    name: 'gcr.io/$PROJECT_ID/kustomize'
    args:
      - 'build'
      - 'overlays/${_ENVIRONMENT}/'
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
      - 'GCLOUD_PROJECT=$PROJECT_ID'
  - id: 'Monitoring Resources'
    name: 'gcr.io/$PROJECT_ID/kustomize'
    args:
      - 'build'
      - 'overlays/${_ENVIRONMENT}-monitoring/'
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
      - 'GCLOUD_PROJECT=$PROJECT_ID'
# Trigger must be set up for substitutions on GCP
substitutions:
  _ENVIRONMENT: 'development'
  _CLUSTER: 'meet-cluster'
  _ZONE: 'northamerica-northeast1-a'
