apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: jitsi
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - video.sentryhealth.dev
    secretName: jitsi-messenger-schule-tls
  rules:
    - host: video.sentryhealth.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: haproxy
              servicePort: 80
