apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: prosody
  name: prosody
spec:
  selector:
    matchLabels:
      shard: "1"
  template:
    metadata:
      labels:
        shard: "1"
